"""empty message

Revision ID: 2f0b5de66068
Revises: d8b68ba0b7d3
Create Date: 2022-05-14 23:36:55.804189

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2f0b5de66068'
down_revision = 'd8b68ba0b7d3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pitches', sa.Column('context', sa.String(), nullable=True))
    op.drop_column('pitches', 'content')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pitches', sa.Column('content', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('pitches', 'context')
    # ### end Alembic commands ###
